### ISSUE TITLE
Handle when entity does not exists

### ISSUE THREAD

**Issue by royto** [cbulock/lovelace-battery-entity#11]
I configure a set of entities with battery level.

I made a typo in one of my entity and none of the battery level was displayed.

Handle entity not found and display error

**Comment by maorcc** [comment]
Same issue when the entity does exist but has an "Unknown" state.

![image](https://user-images.githubusercontent.com/255973/80320149-56ce2100-881d-11ea-8894-3edbf52996aa.png)

**Comment by royto** [comment]
Close as repo not updated for a while and switch to [battery-state-card](https://github.com/maxwroc/battery-state-card)
