### ISSUE TITLE
Card Blacklisted

### ISSUE THREAD

**Issue by PierreScerri** [cbulock/lovelace-battery-entity#33]
Hi

I'm getting 'Repository is Blacklisted' and cannot re-install the card via HACS.

**Comment by syphernl** [comment]
Seems to because of https://github.com/hacs/integration/issues/1464 where they stated "Abandoned, not working properly".
I don't really get why they did so since it's working fine for me, even on the latest HASS.

**Comment by PierreScerri** [comment]
Thank you for the update.
Still can't re-install it.

**Comment by syphernl** [comment]
You might want to add the repo to the custom repos (in HACS, top right dots and then custom repositories). That should hopefully allow you to install it again.Op 15 sep. 2020 14:01 schreef PierreScerri <notifications@github.com>:
Thank you for the update.
Still can't re-install it.

**Comment by PierreScerri** [comment]
Thanks.  I'll try that.

**Comment by bakito** [comment]
I had to fork it to be able to install it as custom repo. The original repo was not allowed, since it is in the default catalog.
