### ISSUE TITLE
alignment off % numbers

### ISSUE THREAD

**Issue by r3mcos3** [cbulock/lovelace-battery-entity#7]
I've installed your battery entity card 
but de alignment off te % number is off 
its really close to the edge. 

![screenshot-hassio local-8123-2019 04 06-07-12-58](https://user-images.githubusercontent.com/45529818/55665212-9d7c6200-583b-11e9-8aa8-f7edc0574b7c.png)

**Comment by r3mcos3** [comment]
This issue is still applicable, I saw you added in HACS. Installed again, but the alignment is still off.

**Comment by Veldkornet** [comment]
I have this issue as well, installed via HACS.

The alignment on the left side and right side is not correct.
